### ISSUE TITLE
是否需要提交StyleCI bot的仓库配置文件？

### ISSUE THREAD

**Issue by medz** [notadd/framework#59]
提交配置文件有助于fork后或者规范commit人员的代码统一fix格式优化，避免因为各自仓库的bot配置不同造成fix方案不一致的问题。
### 需求方案进度：
1. [x] Create Issues.
2. [ ] Confirm requirements.
3. [ ] Pull request code or close issues.

**Comment by windcold** [comment]
可以提交一个pull

**Comment by medz** [comment]
配置文件fix级别设置默认：“psr-2”
